[package]
name = "piston-tut"
version = "0.1.0"
authors = ["Zuhair Rayyes <rayyes.z@ikarus.at>"]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
